### ISSUE TITLE
OidcClient.validateAccessTokenAsync fails if at_hash is not presented

### ISSUE THREAD

**Issue by aslovtsov** [IdentityModel/oidc-token-manager#47]
OidcClient.validateAccessTokenAsync is using at_hash for validation of access_token regardless the fact that it is an optional parameter (http://openid.net/specs/openid-connect-implicit-1_0.html#AccessTokenValidation) and should be used only if presented.
So, if server is not returning at_hash validateAccessTokenAsync fails

```
    if (!id_token_contents.at_hash) {
        return error("No at_hash in id_token");
    }
```

**Comment by brockallen** [comment]
Yep, will look into it. Thx for letting me know.

**Comment by brockallen** [comment]
It says here that `at_hash` is required: https://openid.net/specs/openid-connect-implicit-1_0.html#IDToken

Where do you see that it's optional?

**Comment by brockallen** [comment]
Oh I see, it says: _"The value of at_hash in the ID Token MUST match the value produced in the previous step if at_hash is present in the ID Token. "_

Yea, seems like the spec contradicts itself. Do you really have a OP that does not emit `at_hash`?

Also, perhaps that clause is there in the scenario where you are are making `id_token` requests, instead of `id_token token`.
